To apply RNN on textual data we need to apply numeric conversion so that we can apply RNN on it...

Keras has two apporach to handle text to numbers conversion

    - Integer Encodig
    - Embedding


In [36]:
# Integer encoding SimpleRNN

import numpy as np

docs = ['go india',
    'india india',
    'hip hip hurray',
    'jeetega bhai jeetega india jeetega',
    'bharat mata ki jai',
    'kohli kohli',
    'sachin sachin',
    'dhoni dhoni',
    'modi ji ki jai',
    'inquilab zindabad']

In [37]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer(oov_token='<nothing>')

What this do is create a {word : index} dictionary

oov_token -> Out-Of-Vocabulary Token -> it assign any other new word to 'xyz'

Text to sequence -> Example: "I love Python" → [1, 2, 4]

Count word Frequency -> tokenizer.word_counts

In [38]:
tokenizer.fit_on_texts(docs)

In [39]:
tokenizer.word_index

{'<nothing>': 1,
 'india': 2,
 'jeetega': 3,
 'hip': 4,
 'ki': 5,
 'jai': 6,
 'kohli': 7,
 'sachin': 8,
 'dhoni': 9,
 'go': 10,
 'hurray': 11,
 'bhai': 12,
 'bharat': 13,
 'mata': 14,
 'modi': 15,
 'ji': 16,
 'inquilab': 17,
 'zindabad': 18}

In [40]:
tokenizer.word_counts

OrderedDict([('go', 1),
             ('india', 4),
             ('hip', 2),
             ('hurray', 1),
             ('jeetega', 3),
             ('bhai', 1),
             ('bharat', 1),
             ('mata', 1),
             ('ki', 2),
             ('jai', 2),
             ('kohli', 2),
             ('sachin', 2),
             ('dhoni', 2),
             ('modi', 1),
             ('ji', 1),
             ('inquilab', 1),
             ('zindabad', 1)])

In [41]:
tokenizer.document_count

10

In [42]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[10, 2],
 [2, 2],
 [4, 4, 11],
 [3, 12, 3, 2, 3],
 [13, 14, 5, 6],
 [7, 7],
 [8, 8],
 [9, 9],
 [15, 16, 5, 6],
 [17, 18]]

In [43]:
from tensorflow.keras.utils import pad_sequences

In [44]:
sequences = pad_sequences(sequences, padding='post') # 'post' -> the zero padding will be adding to the end
sequences

array([[10,  2,  0,  0,  0],
       [ 2,  2,  0,  0,  0],
       [ 4,  4, 11,  0,  0],
       [ 3, 12,  3,  2,  3],
       [13, 14,  5,  6,  0],
       [ 7,  7,  0,  0,  0],
       [ 8,  8,  0,  0,  0],
       [ 9,  9,  0,  0,  0],
       [15, 16,  5,  6,  0],
       [17, 18,  0,  0,  0]], dtype=int32)

In [63]:
# Now lets apply it on real dataset

from tensorflow.keras.datasets import imdb
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, SimpleRNN, Embedding, Flatten

In [20]:
(X_train, y_train),(X_test, y_test) = imdb.load_data()

17464789/17464789 ━━━━━━━━━━━━━━━━━━━━ 8s 0us/step


In [22]:
X_train.shape

(25000,)

Since the length of each of the elements within the X_train & X_test are diff so only the no of elements are show ...

In [23]:
X_test.shape

(25000,)

In [28]:
# keeping only 50 words of each scentence to reduce computation
X_train = pad_sequences(X_train, padding='post', maxlen=50)
X_test = pad_sequences(X_test, padding='post', maxlen=50)

In [29]:
X_train.shape

(25000, 50)

In [31]:
model = Sequential()

model.add(SimpleRNN(32, input_shape=(50,1), return_sequences=False))
model.add(Dense(1, activation='sigmoid'))

model.summary()

2025-09-04 18:40:51.943964: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M3
2025-09-04 18:40:51.944038: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 16.00 GB
2025-09-04 18:40:51.944078: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 5.33 GB
2025-09-04 18:40:51.944123: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2025-09-04 18:40:51.944154: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)
/Users/praveenk/Documents/Deep_learning/tf-metal/lib/python3.12/site-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. 

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn (SimpleRNN)          │ (None, 32)             │         1,088 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,121 (4.38 KB)

 Trainable params: 1,121 (4.38 KB)

 Non-trainable params: 0 (0.00 B)

Why keep the return_sequences -> False

As we are perfoming Sentiment analysis so their is no need to output at each step rather we only need the output from the last step.

Named Entity Recognition, Machine Translation -> these are some of the process where we need the output at each step.

![lec_img/rnn_map.png](lec_img/rnn_map.png)

In [32]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

model.fit(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

Epoch 1/5


2025-09-04 21:15:56.390391: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.


782/782 ━━━━━━━━━━━━━━━━━━━━ 460s 586ms/step - accuracy: 0.4951 - loss: 0.6944 - val_accuracy: 0.5027 - val_loss: 0.6965
Epoch 2/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 460s 589ms/step - accuracy: 0.5064 - loss: 0.6933 - val_accuracy: 0.5026 - val_loss: 0.6943
Epoch 3/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 452s 579ms/step - accuracy: 0.5053 - loss: 0.6932 - val_accuracy: 0.5035 - val_loss: 0.6941
Epoch 4/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 471s 602ms/step - accuracy: 0.5111 - loss: 0.6928 - val_accuracy: 0.5028 - val_loss: 0.6951
Epoch 5/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 483s 618ms/step - accuracy: 0.5123 - loss: 0.6923 - val_accuracy: 0.5050 - val_loss: 0.6938


## Embedding

In NLP, word embedding is a term used for representation of the words for text analysis. It is a way of representing words as dense vectors of real numbers instead of treating them as one-hot vectors or simple integers.

    - One-hot encoding: “cat” → [0, 0, 1, 0, 0]
        (very sparse, no meaning captured, large dimensional space)
    - Word embedding: “cat” → [0.25, -0.61, 0.11, 0.89, …]
        (dense, low-dimensional, captures semantic meaning)
So, words that have similar meanings end up with vectors that are close to each other in this embedding space.

Example:

    - “king” and “queen” → vectors are close.
    - “cat” and “dog” → vectors are closer than “cat” and “car”.

In Deep Learning -> keras provide a feature to add embedding layer

In [70]:
# Using the same sequence (which we got from padding)
sequences

array([[10,  2,  0,  0,  0],
       [ 2,  2,  0,  0,  0],
       [ 4,  4, 11,  0,  0],
       [ 3, 12,  3,  2,  3],
       [13, 14,  5,  6,  0],
       [ 7,  7,  0,  0,  0],
       [ 8,  8,  0,  0,  0],
       [ 9,  9,  0,  0,  0],
       [15, 16,  5,  6,  0],
       [17, 18,  0,  0,  0]], dtype=int32)

In [64]:
# adding a embedding layer on it

model = Sequential()

# it takes 3 inputs ... 
#        1. input_len -> Size of vocabulary (maximum integer index + 1); in this case 18 (17+1)
#        2. output_dim -> with how many numbers do you want to represent your words (hyperparameter) -> you tune it and find the best fit
#        3. input_length -> Length of input sequences after padding
model.add(Embedding(input_dim=18, output_dim=2, input_length=5))
model.summary()

Model: "sequential_13"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_11 (Embedding)        │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [51]:
model.compile('adam', 'accuracy')

In [53]:
# now this is the vector reprsentation of each sequences, where each number is represented by 2 numbers
pred = model.predict(sequences)
pred

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step


array([[[-0.01006231,  0.0274003 ],
        [ 0.02420709, -0.00569157],
        [-0.04196298, -0.00540381],
        [-0.04196298, -0.00540381],
        [-0.04196298, -0.00540381]],

       [[ 0.02420709, -0.00569157],
        [ 0.02420709, -0.00569157],
        [-0.04196298, -0.00540381],
        [-0.04196298, -0.00540381],
        [-0.04196298, -0.00540381]],

       [[-0.03428693,  0.01960373],
        [-0.03428693,  0.01960373],
        [-0.00162169, -0.01225429],
        [-0.04196298, -0.00540381],
        [-0.04196298, -0.00540381]],

       [[-0.01451548,  0.02985754],
        [ 0.03135833,  0.00565775],
        [-0.01451548,  0.02985754],
        [ 0.02420709, -0.00569157],
        [-0.01451548,  0.02985754]],

       [[-0.00938318,  0.00428944],
        [ 0.03150119, -0.02018186],
        [ 0.01421146, -0.00475328],
        [ 0.040556  ,  0.01128219],
        [-0.04196298, -0.00540381]],

       [[ 0.03804809, -0.0468017 ],
        [ 0.03804809, -0.0468017 ],
        [-0.041962

## Now lets test using the imdb dataset

we already have the training and testing data

Well which one to use word2vec or adding a embedding layer of keras itself -> well using an embedding layer gives more custom output (which is able to capture more semantic meaning within your dataset)

In [69]:
model = Sequential()

model.add(Embedding(10000, output_dim=2, input_length=50))
model.add(SimpleRNN(32, return_sequences=False))
model.add(Dense(1, activation='sigmoid'))

model.build(input_shape=(None, 50))  # Explicitly build
model.summary()

Model: "sequential_17"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_15 (Embedding)        │ (None, 50, 2)          │        20,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_11 (SimpleRNN)       │ (None, 32)             │         1,120 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 21,153 (82.63 KB)

 Trainable params: 21,153 (82.63 KB)

 Non-trainable params: 0 (0.00 B)

In [68]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
history=model.fit(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

Epoch 1/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 738s 943ms/step - accuracy: 0.6076 - loss: 0.6348 - val_accuracy: 0.8021 - val_loss: 0.4304
Epoch 2/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 771s 986ms/step - accuracy: 0.8395 - loss: 0.3706 - val_accuracy: 0.8089 - val_loss: 0.4208
Epoch 3/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 793s 1s/step - accuracy: 0.8781 - loss: 0.3032 - val_accuracy: 0.7996 - val_loss: 0.4599
Epoch 4/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 861s 1s/step - accuracy: 0.8933 - loss: 0.2744 - val_accuracy: 0.7973 - val_loss: 0.4846
Epoch 5/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 927s 1s/step - accuracy: 0.9103 - loss: 0.2416 - val_accuracy: 0.7909 - val_loss: 0.5403
